# Raspberry Pi 3 Hardware Build Configuration

[target.aarch64-unknown-none-softfloat]
rustflags = [
    "-C", "target-cpu=cortex-a53",
    "-C", "link_arg=--section-start=.text=0xffff000000080000",
]

[target.armv7a-none-eabi]
rustflags = [
    "-C", "target-cpu=cortex-a53",
    "-C", "link_arg=--section-start=.text=0xc0008000",
]

[env]
CPU_aarch64 = "-mcpu=cortex-a53"
CPU_arm = "-mcpu=cortex-a53"
